### ISSUE TITLE
pointless day night cycle

### ISSUE THREAD

**Issue by Skamiz** [veprogames/mt-100mts#13]
Currently the day night cycle doesn't serve any purpose. This doesn't really matter when deep underground, but while near the surface or if you manage to have a long shaft to funnel sunlight into the mine without encountering bedrock, night time is just plain annoying.
Unless there are plans to make the cycle more gameplay relevant I would suggest to just disable it and have permanent day.

**Comment by veprogames** [comment]
yea, agree.

Maybe this can be done by setting a flag or smth. without setting or checking the time every game tick.

**Comment by Skamiz** [comment]
I believe it's possible to set the 'time_speed' setting from code.
The thing to look out for there, is that it still might be possible to change it this way for **_all_** of the players games, which is less then ideal. But maybe that has changed since I last looked into it?
Dealing with settings in Minetest  is kind of messy at times.
