### ISSUE TITLE
impractical light

### ISSUE THREAD

**Issue by Skamiz** [veprogames/mt-100mts#15]
the active coal has a very short light range
I think that is mostly fine for the first tier of lighting, but it also means that you have to place it very close to the area you are working in for it to be effective. Combined with the fact that it is a full node this means that you end up placing it in your way or have to make a nook for it to the side... which is most likely a node further from your work area, which at it's short range is noticeable difference.

Generally while playing I end up very often placing down the light and then immediately digging it up again. Sometimes simply because there is nothing of interest in that corner and I need to preserve my light sources.

Edit:
I have, like, 18 other notes to address btw, But that will have to wait for a later date.

**Comment by veprogames** [comment]
+1 more light_source or +2 could work
speaking of light, I find the night annoying. since theres no monsters anyway I feel like permanent day would feel better

**Comment by veprogames** [comment]
Lights are being rebalanced in #18
