### ISSUE TITLE
sugestion: autogenerate mineral names

### ISSUE THREAD

**Issue by Skamiz** [veprogames/mt-100mts#17]
Since the later minerals (not that I have dug so far yet) are only named things like: "Mineral45", "Mineral 67", etc. it would be nice if they were called something that at least sounds like a real material.

You can see an example of it in Piezo_s unique_ores mod here: [https://notabug.org/Piezo_/unique_ores/src/master/init.lua#L3](url)
Though in Piezo_s code the name is directly tied to the ores properties, the important part is that it's just three tables of strings which get semi randomly strung together to get an unique name.

**Comment by veprogames** [comment]
I had 2 systems in mind

1. Generate random letters in the sequence of [vowel, consonant, vowel, consonant, ...], this makes the random word pronounceable
2. Stick together random english syllables (for example "hard" from "hard", "ter" from "interesting", "char" from "charcoal"), but I don't have a list of single syllables

**Comment by Skamiz** [comment]
I was thinking along the lines of opening up a Wikipedia list of minerals and butchering it for word components. That way, they should hopefully end up sounding somewhat real.

**Comment by veprogames** [comment]
Apart from that, feel free to make a branch where you define a few minerals that you think could be in the game, if you have ideas (MineralList.lua) I will probably add Uranium somewhere inbetween

**Comment by Skamiz** [comment]
On the last point. How do you feel about ores from other Minetest games like Mese, Mithril, Rainbow ore, etc. ?

**Comment by veprogames** [comment]
for Rainbow Ore -> Rainbow Pickaxe the Mineral definition needs to be extended for an optional pickaxe_image, aside from pickaxe_color. Mithril is already there. Mese should be around Citrine or Gold

**Comment by veprogames** [comment]
as #28 was merged, I will close this
