### ISSUE TITLE
travel

### ISSUE THREAD

**Issue by Skamiz** [veprogames/mt-100mts#21]
I noticed that there are milestones now.
One thing that I feel should definitively be addressed before a 1.0 release is travel.

This an issue Minetest game also suffers from, but if the player needs to return to the surface (if for nothing else then to get wood) then they need a way to do so, which isn't mind numbingly boring. In MTG it's possible to build a ladder shaft and even then it can take several minutes of holding down the space bar and nothing else to reach the surface. MTS doesn't even have that

What MTS does have is death. That is, if you have health enabled you can just kill yourself and respawn on the surface with your inventory intact.
Two problems with that. A) with enabled health you can't just throw yourself down the mine shaft, so getting back down would take forever instead, B) I don't think intentionally killing yourself should be part of normal gameplay.

If health isn't enabled, downwards travel can be done easily with gravity and a bit of planing while while mining. Instead he upwards journey is a pain.

For that matter is is the game supposed to be played with or without health?

**Comment by veprogames** [comment]
The player is meant to take damage (there is Magma and Lava underground)

Idea here: #22

**Comment by veprogames** [comment]
Since Teleporters are added, can this be closed?

**Comment by Skamiz** [comment]
sure
